version: 2
updates:
- package-ecosystem: cargo
  directory: "/server"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: syn
    versions:
    - 1.0.60
    - 1.0.62
    - 1.0.64
    - 1.0.67
    - 1.0.68
    - 1.0.69
  - dependency-name: futures-task
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
  - dependency-name: thiserror
    versions:
    - 1.0.23
  - dependency-name: quote
    versions:
    - 1.0.8
  - dependency-name: parking_lot_core
    versions:
    - 0.8.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@wasm-tool/wasm-pack-plugin"
    versions:
    - 1.3.2
    - 1.3.3
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
- package-ecosystem: cargo
  directory: "/client"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: wasm-bindgen-futures
    versions:
    - 0.4.20
    - 0.4.21
    - 0.4.22
  - dependency-name: anyhow
    versions:
    - 1.0.38
    - 1.0.39
  - dependency-name: wasm-bindgen
    versions:
    - 0.2.70
    - 0.2.71
    - 0.2.72
  - dependency-name: web-sys
    versions:
    - 0.3.47
    - 0.3.48
    - 0.3.49
  - dependency-name: http
    versions:
    - 0.2.3
- package-ecosystem: cargo
  directory: "/shared"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serde
    versions:
    - 1.0.122
    - 1.0.123
    - 1.0.124
