[package]
name = "shared"
version = "0.1.0"
authors = ["conectado <conectado2@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
serde = {version = "^1.0", features = ["derive"]}
